spring:
  datasource:
    url: jdbc:mysql://localhost:3306/juastudy?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asas2100

